### PR TITLE
Fixed view profile page, closes #137

### LINKED ISSUE #137: Profile display page is Broken
The profile page is broken since the template is not rendering any user related info.

### PR DESCRIPTION
**Pull request by pnshiralkar**
Closes #137

### CODE REVIEW

**Comment by ankitjavalkar** [comment]
This PR seems to have been rebased incorrectly or has common history with some other branch, it shouldn't have so many commits.

**Comment by pnshiralkar** [comment]
It includes some commits from already merged PRs by mistake.
I don't think this will have conflicts.

**Comment by adityacp** [comment]
LGTM

**Comment by adityacp** [comment]
Tests needs to be fixed but merging for now

**Pull request merged**
